### ISSUE TITLE
visdrone val set test question

### ISSUE THREAD

**Issue by wangxiaoming1886** [ChenhongyiYang/QueryDet-PyTorch#10]
Hi, I train and test QueryDet on VisDrone. However, I can only find the speed(FPS) result. Could you please tell me how to get accurary(AP)? Do you use https://github.com/VisDrone/VisDrone2018-DET-toolkit to get the final AP? 
thank u!

**Comment by ChenhongyiYang** [comment]
Hello,

You can use visdrone/json_to_txt.py to convert the result json file to txt files, then use the official evaluation kit to get the final AP.

Thank you :-)

**Comment by Frank-jinchuan** [comment]
> Hi, I train and test QueryDet on VisDrone. However, I can only find the speed(FPS) result. Could you please tell me how to get accurary(AP)? Do you use https://github.com/VisDrone/VisDrone2018-DET-toolkit to get the final AP? thank u!

Hi, have you get AP sucessfully? How do you do that? Thank you!
