### ISSUE TITLE
How do I apply CSQ to yolo?

### ISSUE THREAD

**Issue by xiaoche-24** [ChenhongyiYang/QueryDet-PyTorch#18]
Thanks for your good job ! I am learning how to improve the detection performance of yolo on small objects . After reading your paper, I got a lot of inspiration. I want to apply CSQ to yolo to see how it works.

**Comment by ChenhongyiYang** [comment]
Hi. We did not test CSQ on YOLO so you need to implement it by yourself. YOLO series have feature pyramid structures so the job is should be easy.

**Comment by xiaoche-24** [comment]
Hi. I have tried to apply CSQ in yolo.But there is a problem,how can i get gt_query in yolo?

**Comment by 23jisuper** [comment]
> @ChenhongyiYang Thank you for your reply. I have tried to apply CSQ in yolo.But there is a problem,how can i get gt_query in yolo?

您好！请问在yolo上实现了吗？
