### ISSUE TITLE
Invoked 'with amp.scale_loss`, but internal Amp state has not been initialized

### ISSUE THREAD

**Issue by JohnPekl** [ChenhongyiYang/QueryDet-PyTorch#19]
Thank you for publishing this source code.

I am trying to retrain `QueryDet-PyTorch` on MS-COCO but face the following error.

> RuntimeError: Invoked 'with amp.scale_loss`, but internal Amp state has not been initialized.  model, optimizer = amp.initialize(model, optimizer, opt_level=...) must be called before `with amp.scale_loss`.

Amp state is initialized if `comm.get_world_size() > 1`. I guess you haven't handled when `comm.get_world_size() == 1`.

**Comment by ChenhongyiYang** [comment]
Hi John. Yes, all my experiments were done in 8 GPU settings. So I did not realize that there would be problems in the single-GPU setting. Sorry about this.

**Comment by YuxuanWen-Code** [comment]
> 

Hi, how did you solve this problem eventually, can I just directly edit the source code of apex?

**Comment by itsrealkk** [comment]
> > 
> 
> Hi, how did you solve this problem eventually, can I just directly edit the source code of apex?

Same problem here. It seems that you need to modify the line 87 in apex_trainer.py file. but i dont know how to modify it

**Comment by bhargavipatel** [comment]
Anyone was able to solve this issue for 1 gpu ?

**Comment by sotoy** [comment]
You can just move the ```python model, optimizer = amp.initialize(model, optimizer, opt_level=opt_level)``` above the ```python comm.get_world_size() > 1``` condition.
