### ISSUE TITLE
请问我运行的时候，一直提示找不到路径是什么原因啊，我想知道在哪里可以修改路径呢

### ISSUE THREAD

**Issue by DCkami** [ChenhongyiYang/QueryDet-PyTorch#20]
![image](https://user-images.githubusercontent.com/89574100/164879348-26b0db5c-0f98-4520-b209-9ae1959bbf93.png)

**Comment by ChenhongyiYang** [comment]
Hi. You need to replace the "path/to/label.json" with the real COCO annotation path.
