### ISSUE TITLE
i

### ISSUE THREAD

**Issue by python0527** [ChenhongyiYang/QueryDet-PyTorch#21]
![EP)YQ 5_`2XU82BR%KI47A](https://user-images.githubusercontent.com/87927277/166428425-93d7f14f-754d-446f-b740-1954343bd1cf.png)

明明有这个包 但代码里确找不到

**Comment by ChenhongyiYang** [comment]
Hi. 

In this case, you can run the code directly, otherwise, you need to properly set up the python environment in your IDE.
