### ISSUE TITLE
请问torch版本必须是1.4吗

### ISSUE THREAD

**Issue by BEVISjyy** [ChenhongyiYang/QueryDet-PyTorch#22]
251, in run_step
    self._detect_anomaly(losses, loss_dict)
AttributeError: 'Trainer' object has no attribute '_detect_anomaly'
请问是不是我的torch版本不对，所以导致的这个问题呢？谢谢！

**Comment by ChenhongyiYang** [comment]
Hi. We tested all our code using torch 1.4, but I think the new versions should also work.

**Comment by BEVISjyy** [comment]
好的，谢谢！

**Comment by oopsboy** [comment]
> 好的，谢谢！

@BEVISjyy  请问你是如何解决的？我也出现了这样的问题
