### ISSUE TITLE
I have a request，thank you.

### ISSUE THREAD

**Issue by 1huyouquan** [ChenhongyiYang/QueryDet-PyTorch#24]
I am very interested in your excellent work. Can you give an introduction to the function of each file？thank you.
对您优秀的工作十分感兴趣，请问，可以给一个每个文件大概做了什么（也就是每个文件的作用）的介绍（说明）吗？十分感谢。

**Comment by ChenhongyiYang** [comment]
Hello. Thank you for being interested in our work. Our implementation is based on [Detectron2](https://github.com/facebookresearch/detectron2). Thus you may need to read its code first.
