### ISSUE TITLE
可以和其他label assign进行融合吗

### ISSUE THREAD

**Issue by sdreamforchen** [ChenhongyiYang/QueryDet-PyTorch#29]
您好，感觉这也是一种label assign方法，是不是只能单用呢？

**Comment by ChenhongyiYang** [comment]
Hi. Thank you for noticing our work. We used the default label assignment approach for training the detection heads (classification and regression). 

The label assignment strategy for the small object heatmap was specifically designed for the query purpose: We wanted the activation area for a particular small object to be related to the object's size, so we do not need query useless pixels for very small objects or insufficient pixels for relatively large objects. 

We are not sure if this assignment strategy works well for general object detection, but we think this is an interesting idea. You may have a try by yourself, and it would be fantastic if you can share the results.  :-)
