### ISSUE TITLE
Why can CSP speed up three times？

### ISSUE THREAD

**Issue by nicehuster** [ChenhongyiYang/QueryDet-PyTorch#3]
Thanks for your wanderful jobs，The amount of parameters in the last two lines should be roughly the same, so the amount of computation should be the same. Why can CSQ speed up three times? Is it because of sparse convolution?
![image](https://user-images.githubusercontent.com/35832232/113119968-a2662780-9243-11eb-8708-f77573661440.png)

**Comment by ChenhongyiYang** [comment]
Yep, this is our main contribution. We will public our code next week, so you can have a try by yourself then :-)

**Comment by nicehuster** [comment]
> Yep, this is our main contribution. We will public our code next week, so you can have a try by yourself then :-)

xiang

> Yep, this is our main contribution. We will public our code next week, so you can have a try by yourself then :-)

thanks for your reply, i can't wait for your codes
