### ISSUE TITLE
visdrone training is pulling and doing coco dataset training

### ISSUE THREAD

**Issue by bhargavipatel** [ChenhongyiYang/QueryDet-PyTorch#30]
I am trying to train on visdrone and the code is pulling coco_train.py from the train_tools instead of visdrone_train.py Can you please look into this ?

**Comment by ChenhongyiYang** [comment]
Hi, please try [train_visdrone.py](https://github.com/ChenhongyiYang/QueryDet-PyTorch/blob/main/train_visdrone.py) for VisDrone experiments.
