### ISSUE TITLE
Hello,when i run the train_coco.py,i came across a bug:'AttributeError: 'Trainer' object has no attribute '_detect_anomaly',could you help me?

### ISSUE THREAD

**Issue by bling-bling-only** [ChenhongyiYang/QueryDet-PyTorch#33]
Traceback (most recent call last):
  File "train_coco.py", line 15, in <module>
    launch(
  File "/home/lei/anaconda3/envs/py38/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/lei/Project/QueryDet-PyTorch-main*/train_tools/coco_train.py", line 177, in start_train
    return trainer.train()
  File "/home/lei/Project/QueryDet-PyTorch-main*/apex_tools/apex_trainer.py", line 227, in train
    self.run_step()
  File "/home/lei/Project/QueryDet-PyTorch-main*/apex_tools/apex_trainer.py", line 251, in run_step
    self._detect_anomaly(losses, loss_dict)
AttributeError: 'Trainer' object has no attribute '_detect_anomaly'

**Comment by choasup** [comment]
I meet the same problem...

**Comment by bling-bling-only** [comment]
你用的apex的版本是什么，跟作者的一样吗

**Comment by XinZhangNLPR** [comment]
I met the same problem.
The problem is that the version number of detectron2 should be 0.2.1. Some versions of detectron2 delete the _ detect_anomaly from the Class SimpleTrainer,  such as detectron2 in version 3.0. 

Therefore, it is recommended that you install detectron2 version 0.2.1

**Comment by bling-bling-only** [comment]
thank you for your reply.I once suspected that it was the version of detection2, but since the computer's graphics card is 30 series, only version 3.0 of detection2 is supported at least.Your answer confirmed my suspicions.

**Comment by sotoy** [comment]
> thank you for your reply.I once suspected that it was the version of detection2, but since the computer's graphics card is 30 series, only version 3.0 of detection2 is supported at least.Your answer confirmed my suspicions.

You can still circumvent this issue by adding the following function inside the ApexTrainer class:
`def _detect_anomaly(self, losses, loss_dict):
        if not torch.isfinite(losses).all():
            raise FloatingPointError(
                "Loss became infinite or NaN at iteration={}!\nloss_dict = {}".format(
                    self.iter, loss_dict
                )
            )`

**Comment by ChenhongyiYang** [comment]
Hi, this problem is caused by the APEX library. We have recently updated the whole repository, and you do not need APEX any more.
