### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/retinanet/configs/coco/path/to/QueryDet-Pytorch/configs/BaseRetina.yaml'

### ISSUE THREAD

**Issue by Frank-jinchuan** [ChenhongyiYang/QueryDet-PyTorch#34]
when i run the code, i aways met  this problem, QueryDet-Pytorch don't have this file and directory, i don't konw how to slove the problem,could you help me?

**Comment by furh95** [comment]
Change _BASE_ in train/test.yaml to '/home/xx/xx/QueryDet-PyTorch/configs/BaseRetina.yaml' (like absolute path)

**Comment by Frank-jinchuan** [comment]
> Change _BASE_ in train/test.yaml to '/home/xx/xx/QueryDet-PyTorch/configs/BaseRetina.yaml' (like absolute path)

Thank you so much. I have solved it. My english is so poor ,i'm happy that you can konw what i say.hahahaha.
