### ISSUE TITLE
ModuleNotFoundError: No module named 'models.backbone'

### ISSUE THREAD

**Issue by jy-Hamlet** [ChenhongyiYang/QueryDet-PyTorch#4]
Thanks for your wonderful jobs，but I got an error when trying to train a retinanet baseline:

> $python train_coco.py --config-file models/retinanet/configs/coco/train.yaml --num-gpu 4 OUTPUT_DIR workdir
Traceback (most recent call last):
  File "train_coco.py", line 9, in <module>
    from train_tools.coco_train import default_argument_parser, start_train
  File "/disk1/qdworkspace/QueryDet-PyTorch/train_tools/coco_train.py", line 53, in <module>
    from models.backbone import build
ModuleNotFoundError: No module named 'models.backbone'

It seems that the program is looking for a file 'models.backbone' but there is no backbone.py in QueryDet-PyTorch/models/ ?

**Comment by ChenhongyiYang** [comment]
Please comment out this line and have a try. Additionally, you may need to modify the batch size to 8  if you are using 4 GPUs,.

**Comment by jy-Hamlet** [comment]
There are still some modules not found in coco_train.py:

> from detectron2_backbone.config import add_backbone_config
import detectron2_backbone.backbone.mobilenet

and the function add_backbone_config() is actually used in coco_train.py and coco_infer.py, how to deal with this?

**Comment by ChenhongyiYang** [comment]
Oh, I'm sorry, you will also need to install [detectron2_backbone](https://github.com/sxhxliang/detectron2_backbone). I have updated the readme.

**Comment by jy-Hamlet** [comment]
Thanks! I can run the training now.
