### ISSUE TITLE
The categories problem during training the VisDrone dataset

### ISSUE THREAD

**Issue by Cuogeihong** [ChenhongyiYang/QueryDet-PyTorch#41]
While training the RetinaNet baseline using your splited VisDrone dataset, I find the processed dataset has only 9 categories. In the [visdrone/data_prepare.py](https://github.com/ChenhongyiYang/QueryDetPyTorch/blob/main/visdrone/data_prepare.py), I find these codes 

```def make_json(images, annotations, new_label_json):
    ann_dict = {}
    ann_dict['categories'] = [
        {'supercategory': 'things', 'id': 1, 'name': 'people'},
        {'supercategory': 'things', 'id': 2, 'name': 'bicycle'},
        {'supercategory': 'things', 'id': 3, 'name': 'car'},
        {'supercategory': 'things', 'id': 4, 'name': 'van'},
        {'supercategory': 'things', 'id': 5, 'name': 'truck'},
        {'supercategory': 'things', 'id': 6, 'name': 'tricycle'},
        {'supercategory': 'things', 'id': 7, 'name': 'awning-tricycle'},
        {'supercategory': 'things', 'id': 8, 'name': 'bus'},
        {'supercategory': 'things', 'id': 9, 'name': 'motor'}
    ]
    ann_dict['images'] = images
    ann_dict['annotations'] = annotations
    with open(new_label_json, 'w') as outfile:
        json.dump(ann_dict, outfile)
```

Does that mean the people and pedestrian categories are merged? 
However, I can't find the merge part, the label's category_id seems to be exactly the same as the category_id from annotations‘ txt file. Maybe there exist some mistakes?

**Comment by Alasile** [comment]
> Does that mean the people and pedestrian categories are merged?
> However, I can't find the merge part, the label's category_id seems to be exactly the same as the category_id from annotations‘ txt file. Maybe there exist some mistakes?
Have you solved this problem? If it is solved, can you tell me the solution, thank you

**Comment by Cuogeihong** [comment]
> > Does that mean the people and pedestrian categories are merged?
> > However, I can't find the merge part, the label's category_id seems to be exactly the same as the category_id from annotations‘ txt file. Maybe there exist some mistakes?
> > Have you solved this problem? If it is solved, can you tell me the solution, thank you

It seems these categories have little influence on training or testing phase, so just ignore it.

**Comment by ChenhongyiYang** [comment]
Hi, there was a bug in the previous version of data_prepare.py. We have fixed it now.
