### ISSUE TITLE
infer in visdrone when uses csq!

### ISSUE THREAD

**Issue by jigongbao** [ChenhongyiYang/QueryDet-PyTorch#42]
when i use queydet to train in visdrone, everything is ok, but when i infer in visdrone, there is some issues about spconv.
![image](https://user-images.githubusercontent.com/96114577/181589814-5fb8e7b9-5022-4159-a084-1292de57af2b.png)
the spconv`s version is 2.x

**Comment by XinZhangNLPR** [comment]
I met the problem. The spconv is only used in inference, that's why there is no problem in training. 
I have tried the spconv-cu102-2.1.21, spconv-cu102-2.1.19,spconv-cu102-2.1.5, it still doesn't work.

**Comment by jigongbao** [comment]
> I met the problem. The spconv is only used in inference, that's why there is no problem in training. I have tried the spconv-cu102-2.1.21, spconv-cu102-2.1.19,spconv-cu102-2.1.5, it still doesn't work.

maybe it`s because the code is based pm spconv 1.x? i find that the usage of spconv is based on spconv 1.x

**Comment by jigongbao** [comment]
i try to replace spconv 2.x with spconv 1.2.1 and i successfully run infer_visdrone.py
