### ISSUE TITLE
Can you provide a portfolio of environments that can run this project?

### ISSUE THREAD

**Issue by xiyanbupapang** [ChenhongyiYang/QueryDet-PyTorch#44]
According to the project instructions and computer configuration, I built pytorch1.4+cuda10.1+detectron2-0.2.1 on a windows system, but pytorch1.4.0 does not support windows distributed training (the error is ==== AttributeError: module 'torch.distributed' has no attribute 'deprecated'), is there a successful configuration for a higher version? Or should I re-build this version of the environment on a linux system?

**Comment by bhargavipatel** [comment]
Hello, here is the one that worked for me, 
[Link from another issue](https://github.com/ChenhongyiYang/QueryDet-PyTorch/issues/38#issuecomment-1198919918l)

**Comment by xiyanbupapang** [comment]
> Hello, here is the one that worked for me, [Link from another issue](https://github.com/ChenhongyiYang/QueryDet-PyTorch/issues/38#issuecomment-1198919918l)

Thank you very much, I have seen your answer in another comment section and tried the environment build you gave, but still have the same problem :AttributeError: module 'torch.distributed' has no attribute 'deprecated' ,.........I think there may have been some problems with the installation of detectron2-2.0.1
I will try again.Thanks again for your answer!
