### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by ly391** [ChenhongyiYang/QueryDet-PyTorch#53]
''Non-existent config key: META_INFO.EVAL_SMALL_CLS'' appears when I test the trained model，

**Comment by S-lyn-0422** [comment]
hello,I also meet this problem.  How did you solve it later?  thanks

**Comment by guanyujer** [comment]
Hi,sorry to bother you,I also met the problem.How did you solve the problem，please.

**Comment by minigemzhen** [comment]
Could you please tell me how you solved this problem?
