### ISSUE TITLE
infer_visdrone.py AssertionError     assert filters.is_contiguous()

### ISSUE THREAD

**Issue by XuKer** [ChenhongyiYang/QueryDet-PyTorch#56]
self.act_type)
  File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward
    raise e
  File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward
    act_type)
  File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm
    assert filters.is_contiguous()
AssertionError

有没有在visdrone上测试的，我运行下面这个直接报错了

python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True

**Comment by Hiyuur** [comment]
> self.act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd return fwd(*args, **kwargs) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward raise e File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm assert filters.is_contiguous() AssertionError
> 
> 有没有在visdrone上测试的，我运行下面这个直接报错了
> 
> python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True

我也出现了这个错误，我用的spconv 2.x

**Comment by XuKer** [comment]
> 



> > self.act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd return fwd(*args, **kwargs) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward raise e File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm assert filters.is_contiguous() AssertionError
> > 有没有在visdrone上测试的，我运行下面这个直接报错了
> > python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True
> 
> 我也出现了这个错误，我用的spconv 2.x

我也是spconv2, cuda 10.2  你找到解决办法了吗？

**Comment by yuzhi535** [comment]
> self.act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd return fwd(*args, **kwargs) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward raise e File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm assert filters.is_contiguous() AssertionError
> 
> 有没有在visdrone上测试的，我运行下面这个直接报错了
> 
> python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True

我也出现了这个错误，spconv2, cuda11.3。请问找到解决方法了吗？

**Comment by Hiyuur** [comment]
> > 
> 
> > > self.act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd return fwd(*args, **kwargs) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward raise e File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm assert filters.is_contiguous() AssertionError
> > > 有没有在visdrone上测试的，我运行下面这个直接报错了
> > > python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True
> > 
> > 
> > 我也出现了这个错误，我用的spconv 2.x
> 
> 我也是spconv2, cuda 10.2 你找到解决办法了吗？

最简单的办法是使用spconv1.2.1

**Comment by Hiyuur** [comment]
> > self.act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd return fwd(*args, **kwargs) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward raise e File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm assert filters.is_contiguous() AssertionError
> > 有没有在visdrone上测试的，我运行下面这个直接报错了
> > python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True
> 
> 我也出现了这个错误，spconv2, cuda11.3。请问找到解决方法了吗？

换spconv1.2.1

**Comment by yuzhi535** [comment]
> > > self.act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 209, in decorate_fwd return fwd(*args, **kwargs) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 224, in forward raise e File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 214, in forward act_type) File "/root/anaconda3/envs/querydet/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1467, in implicit_gemm assert filters.is_contiguous() AssertionError
> > > 有没有在visdrone上测试的，我运行下面这个直接报错了
> > > python infer_visdrone.py --config-file models/querydet/configs/visdrone/test.yaml --num-gpu 1 --eval-only MODEL.WEIGHTS / /out/model_final.pth MODEL.QUERY.QUERY_INFER True
> > 
> > 
> > 我也出现了这个错误，spconv2, cuda11.3。请问找到解决方法了吗？
> 
> 换spconv1.2.1

感谢大佬，终于成功了
