### ISSUE TITLE
About VirDrone： data_prepare.py

### ISSUE THREAD

**Issue by myc1998** [ChenhongyiYang/QueryDet-PyTorch#58]
def make_json(images, annotations, new_label_json):
    ann_dict = {}
    ann_dict['categories'] = [
        {'supercategory': 'things', 'id': 1, 'name': 'pedestrian'},
        {'supercategory': 'things', 'id': 2, 'name': 'people'},
        {'supercategory': 'things', 'id': 3, 'name': 'bicycle'},
        {'supercategory': 'things', 'id': 4, 'name': 'car'},
        {'supercategory': 'things', 'id': 5, 'name': 'van'},
        {'supercategory': 'things', 'id': 6, 'name': 'truck'},
        {'supercategory': 'things', 'id': 7, 'name': 'tricycle'},
        {'supercategory': 'things', 'id': 8, 'name': 'awning-tricycle'},
        {'supercategory': 'things', 'id': 9, 'name': 'bus'},
        {'supercategory': 'things', 'id': 10, 'name': 'motor'}
    ]
There is no id=0 setting. When you are training, you will find no categories_ id=0 in the json file?

**Comment by Alasile** [comment]
> 

Have you solved this problem? If it is solved, can you tell me the solution, thank you

**Comment by myc1998** [comment]
A simple correspondence needs to be made here. For example, id: 1->0. When processing datasets in the code, the id is automatically set to start looking from 0.
Hope it works for you.

**Comment by qidudu** [comment]
Hi, how exactly is this sentence realised：“For example, id: 1->0. When processing datasets in the code, the id is automatically set to start looking from 0.”

**Comment by qidudu** [comment]
> A simple correspondence needs to be made here. For example, id: 1->0. When processing datasets in the code, the id is automatically set to start looking from 0. Hope it works for you.

Hi, how exactly is this sentence realised：“For example, id: 1->0. When processing datasets in the code, the id is automatically set to start looking from 0.”
