### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by PJPomPom** [ChenhongyiYang/QueryDet-PyTorch#60]
PermissionError: [Errno 13] Permission denied: '/path'
![image](https://user-images.githubusercontent.com/77728649/207378299-87c8782a-03bb-4c46-b2e9-1dc978cf1dee.png)

**Comment by ChenhongyiYang** [comment]
Hi, thanks for being interested in our work. You need to specify the path of your own instead of using the default one. THX!
