### ISSUE TITLE
What part of the source code is spconv x4 in Figure 3.?

### ISSUE THREAD

**Issue by Keiku** [ChenhongyiYang/QueryDet-PyTorch#7]
> Then the sparse convolution [14] (spconv) kernels are built using weights of the 4-conv dense heads to compute results on layer l − 1.

I'm studying your QueryDet now, but I didn't understand this description on the paper. Where is spconv x4 written in the code?

**Comment by ChenhongyiYang** [comment]
Thanks for your interest. It's in [models/querydet/qinfer.py](https://github.com/ChenhongyiYang/QueryDet-PyTorch/blob/main/models/querydet/qinfer.py), the _make_spconv function.

**Comment by Keiku** [comment]
I'm sorry for the simple question. I understand.
