### ISSUE TITLE
figure 5 heatmap

### ISSUE THREAD

**Issue by liang532** [ChenhongyiYang/QueryDet-PyTorch#9]
this repository is a great work , thank you for your open source.
I want to know how to draw this heatmap , is that heatmap a class activate map(CAM)?
![P9M_L6660`98ON) R1UX 0R](https://user-images.githubusercontent.com/72304708/129477831-af0904a2-4716-44df-bd29-b9aa78148e5c.png)

**Comment by ChenhongyiYang** [comment]
Hello, they are simply the score maps output by the Query Head.

**Comment by liang532** [comment]
Thanks for your answer.
