### ISSUE TITLE
Does the environment configuration affect the experimental results?

### ISSUE THREAD

**Issue by liuw20** [ChenhongyiYang/QueryDet-PyTorch#96]
my environment：
RTX 3090+Pytorch1.12.0+cu113+detectron0.6

my result:
![image](https://github.com/ChenhongyiYang/QueryDet-PyTorch/assets/72062754/cf4ae539-4d43-4181-ab55-22cf13e6152c)

I trained retinanet and querydet with the default config，but the results  are not same with the paper. Is it because of environmental issues?

**Comment by liuw20** [comment]
visdrone+2019

**Comment by liuw20** [comment]
I adjust the version of spconv to 'spconv-cu113==2.1.25'，the result is perfect! So the version of spconv must be matched with the cuda version!

**Comment by judycpChen** [comment]
> I adjust the version of spconv to 'spconv-cu113==2.1.25'，the result is perfect! So the version of spconv must be matched with the cuda version!

Hello ,do you have this problem?
NotImplementedError: SPCONV_FILTER_HWIO is deprecated. use SPCONV_SAVED_WEIGHT_LAYOUT instead.

**Comment by judycpChen** [comment]
> I adjust the version of spconv to 'spconv-cu113==2.1.25'，the result is perfect! So the version of spconv must be matched with the cuda version!

Hello, I would like to know how your configuration is, your platform is windows or other
